services:
  Wakeapp\Bundle\SystemStatusBundle\Controller\StatusController:
    public: true
    tags:
      - { name: 'controller.service_arguments' }

  Wakeapp\Bundle\SystemStatusBundle\Service\AuthService:
    autowire: true
    autoconfigure: true
    public: true
    arguments:
      - '%system_status.api_key%'

  Wakeapp\Bundle\SystemStatusBundle\Service\SystemStatusPartService: ~

  Wakeapp\Bundle\SystemStatusBundle\Service\SystemStatusService: ~
